Jose-AE/medspace-frontend

src/components/ReviewStars/ReviewStars.stories.ts, src/components/ReviewStars/ReviewStars.tsx, src/components/ReviewStars/index.ts, src/components/TenantProfileCard/TenantProfileCard.stories.ts, src/components/TenantProfileCard/TenantProfileCard.tsx, src/components/TenantProfileCard/index.ts
This PR finalizes the TenantProfileCard component with the following updates:
- Component Structure:
- Added the initial structure and layout for the TenantProfileCard.
- Integrated ReviewStars to display tenant ratings.
- Implemented primary and public variants for the profile card.
- Styling and Icons:
- Utilized react-icons for phone and email icons to enhance the user interface.
- Applied consistent styling using Tailwind CSS for a cohesive look.
=> Adding tenant profile card

src/components/ClinicImageInput/ClinicImageInput.stories.ts, src/components/ClinicImageInput/ClinicImageInput.tsx, src/components/ClinicImageInput/index.ts, src/components/FileInput/FileInput.stories.ts, src/components/FileInput/FileInput.tsx, src/components/FileInput/index.ts
This mr implements the input components used during clinic creation: file input and image input.
This is part of the following task:
[Jira task](https://paez-tec.atlassian.net/jira/software/projects/MED/boards/2?selectedIssue=MED-71)
- Add FileInput component and documentation
- Add ClinicImageInput component and documentation
All the components introduced are correctly designed
FileInput
ClinicImageInput
=> Add create clinic inputs

package-lock.json, package.json, src/components/RentCalendar/RentCalendar.stories.ts, src/components/RentCalendar/RentCalendar.tsx, src/components/RentCalendar/index.ts, src/lib/dateUtils.ts
This pr adds a new RentCalendar component that visually renders the appointments of a tenant in the form of a calendar.
- Add RentCalendar component and documentation
- Installs the date-fns library to handle date operations
The component is implemented according to the design
=> Add rent calendar component

package-lock.json, package.json, src/components/Charts/EarningsChart/EarningsChart.stories.ts, src/components/Charts/EarningsChart/EarningsChart.tsx, src/components/Charts/EarningsChart/index.ts
This pr adds EarningsChart component 
- Create EarningsChart component
- Add recharts to package.json
The component is implemented according to the design
=> feat: add EarningsChart component with stories and integrate recharts

src/components/RentRequest/RentRequest.tsx, src/components/RentRequest/index.ts
This PR adds the RentRequest component that visually renders a form for users to request a clinic rental. The component includes placeholders for a calendar, a time range selector, and a comment box, along with buttons for submitting or canceling the request.
=> RentRequest base

package-lock.json, package.json, src/components/AvailabilityCalendar/AvailabilityCalendar.stories.ts, src/components/AvailabilityCalendar/AvailabilityCalendar.tsx, src/components/AvailabilityCalendar/index.ts, src/components/RentRequest/RentRequest.stories.ts, src/components/RentRequest/RentRequest.tsx, src/components/TenantComment/TenantComment.stories.ts, src/components/TenantComment/TenantComment.tsx, src/components/TenantComment/index.ts, src/components/ui/button.tsx, src/components/ui/calendar.tsx
This PR implements a new rent request flow with an availability calendar using shadcn/ui. Key changes include:
- Added availability calendar with multiple day selection
- Created TenantComment component for request feedback
- Removed unnecessary UI elements (time range selector, date visualizer)
- Fixed modal styling and improved overall UX
Here are the images:
=> Feature availability calendar

package-lock.json, package.json, src/components/SearchFilter/SearchFilter.stories.ts, src/components/SearchFilter/SearchFilter.tsx, src/components/SearchFilter/index.ts, src/components/ui/toggle.tsx
feat(SearchFilter): Enhance component styling and functionality
- Add click-outside behavior for equipment dropdown
- Update toggle buttons with rounded corners and modern design
- Implement consistent color scheme with brand blue (#1D8BF9)
- Replace heart icon with outline version for better visual harmony
- Improve responsive layout with proper spacing and flex behavior
=> Adding components from shadcn Toggle and finishing SearchFilter

src/components/ClinicsList/ClinicsList.stories.ts, src/components/ClinicsList/ClinicsList.tsx, src/components/ClinicsList/index.ts
New `ClinicsList` component that displays clinic cards with image, title, features, rating, reviews, price, and favorite toggle functionality.
- Created `ClinicsList` components
- Added favorite toggle with heart icons
- Implemented rating display and review count
- Added price display with flexible unit
- Responsive layout with Tailwind CSS
=> Feature clinics list

src/app/create-clinic/layout.tsx, src/app/create-clinic/page.tsx, src/components/MultistepFormNavItem/MultistepFormNavItem.tsx, src/components/Navbar/Navbar.tsx
This PR adds a new frontend route `/create-clinic` that renders the base for a multi-step form to create a clinic.
Closes this [Jira task](https://paez-tec.atlassian.net/browse/MED-12?atlOrigin=eyJpIjoiYTVmNjYyZmNiMzI1NDAyNWFmY2M2ZmQ0OThmNWQwM2IiLCJwIjoiaiJ9)
It will be followed up with PRs that actually implement the form.
- Add create-clinic layout and page
Navigation works correctly in mobile:
Navigation works correctly in desktop:
=> Feature: Setup base for Clinic form

src/components/TextInput/TextInput.tsx
=> fix(TextInput): fix type definitions to work with text area and pass

package-lock.json, package.json, src/app/auth/login/page.tsx, src/app/auth/register/page.tsx, src/app/auth/register/steps/BasicInfoSection.tsx, src/app/auth/register/steps/DocumentsSection.tsx, src/app/layout.tsx, src/components/FileInput/FileInput.tsx, src/hooks/useForm.ts, src/lib/firebase/serverApp.ts, src/services/AuthService.ts, src/services/UserService.ts, src/types/serviceTypes.ts, src/types/userTypes.ts
This PR implements comprehensive sign-up functionality for all three user types (Analyst, Tenant, and Landlord) in the MedSpace platform. The implementation includes a multi-step registration form with basic information collection and document upload capabilities tailored to each user type.
- Added multi-step registration form with navigation between steps
- Added form validation for each step with appropriate error handling
- Added file upload functionality for profile pictures and required documents
- Added specialty selection for Tenant user type
- Added `react-hot-toast` to package.json to add toast component for success/error notifications 
- Improved login page with more descriptive error messages
- Added form data management with custom hook `useForm` for better state handling
- …
=> feature(SignUp):Done all 3 user types sign up page

package-lock.json, package.json, src/app/auth/login/page.tsx, src/app/auth/register/page.tsx, src/app/auth/register/steps/BasicInfoSection.tsx, src/app/auth/register/steps/DocumentsSection.tsx, src/app/layout.tsx, src/components/FileInput/FileInput.tsx, src/hooks/useForm.ts, src/lib/firebase/serverApp.ts, src/services/AuthService.ts, src/services/UserService.ts, src/types/serviceTypes.ts, src/types/userTypes.ts
This PR integrates the finished sign up flow for the 3 user types into the main branch.
=> Feature: Add signup flow

src/app/main/landlord/create-clinic/page.tsx, src/app/main/landlord/create-clinic/steps/BasicInfoSection.tsx, src/app/main/landlord/create-clinic/steps/RentDataSection.tsx, src/app/main/landlord/create-clinic/useCreateClinicForm.tsx, src/components/ClinicAvailabilityInput/ClinicAvailabilityInput.tsx
This PR increments the base create Clinic form to include the Basic Info section. It also adds a useCreateClinicForm hook to handle multi step form logic.
This PR closes the following Jira tasks:
[MED-16](https://paez-tec.atlassian.net/browse/MED-16?atlOrigin=eyJpIjoiMjVkYjUwYTk3ZWFlNGMxNWE4ZTY4ZTYxODQxMjViYmUiLCJwIjoiaiJ9)
[MED-18](https://paez-tec.atlassian.net/browse/MED-18?atlOrigin=eyJpIjoiZjExYjlkMWI4OGZkNDM0ODhjMzAxMGQwNDgzNWIzN2UiLCJwIjoiaiJ9)
Follow Up: Update the form to send a POST request to the backend on submit, creating the Clinic, ClinicAvailability and ClinicEquipment entities.
- Implement numeric inputs in RentDataSection
- Implement ClinicAvailability component in RentDataSection
- Update formData in useCreateClinicForm hook
=> Feature: Clinic form rent data section

src/app/main/landlord/create-clinic/page.tsx, src/hooks/useCreateClinicForm.ts, src/services/ClinicService.ts, src/types/clinicTypes.ts
This PR introduces the `ClinicService`, with a method to POST a request to `/clinics` to be used when submitting the create Clinic Form
=> Feature: Add submit form method

src/app/auth/login/page.tsx, src/app/auth/register/page.tsx, src/app/main/analyst/layout.tsx, src/components/Navbar/Navbar.tsx, src/providers/AuthProvider.tsx, src/services/AuthService.ts, src/services/UserService.ts
This PR replaces direct `window.location` navigation with Next.js's Router API (`useRouter`) across the application to ensure proper client-side navigation with better performance and consistency with Next.js best practices.
- Replace `window.location.href` with `router.push()` in login, register, and logout flows
- Remove `false` state from user authentication context to simplify type handling
- Fix user authentication state to be either `User | null` instead of `User | null | false`
- Add delay for new user creation to ensure proper database synchronization
- Simplify auth headers method to remove unnecessary content-type parameter
- Add file size validation for uploaded documents (max 2MB)
- Improve error messaging for document uploads
=> Fix auth bugs

src/lib/firebase/firebaseApp.ts, src/services/StorageService.ts
This PR implements a StorageService that connects to Firebase Storage, to allow for upload and download of files. 
The firebase project is already configured with a bucket to store files, and requires authentication for read and write operations
:)
=> feature(storage): setup firebase storage service

src/app/main/landlord/create-clinic/page.tsx, src/app/main/landlord/create-clinic/steps/PhotosSection.tsx, src/components/ClinicImageInput/ClinicImageInput.tsx, src/hooks/useCreateClinicForm.ts, src/types/clinicTypes.ts
This PR implements the Clinic Photo section of the creation form, with its corresponding validations and input handling
This PR closes [Jira Task](https://paez-tec.atlassian.net/browse/MED-17?atlOrigin=eyJpIjoiYTE4ZGFkMDkyMDYwNDY2ZWI3ZTcwZmQyNzM4NTNhYWMiLCJwIjoiaiJ9)
=> Feature: implement Clinic photo section

src/app/main/landlord/create-clinic/page.tsx, src/app/main/landlord/create-clinic/steps/BasicInfoSection.tsx, src/app/main/landlord/create-clinic/steps/PhotosSection.tsx, src/app/main/landlord/create-clinic/steps/RentDataSection.tsx, src/app/main/landlord/create-clinic/steps/StepSectionBase.tsx, src/hooks/useCreateClinicForm.ts, src/hooks/useForm.ts
This PR introduces error handling into the existing useForm hook, so that all forms across the app have consistent error validation logic
- Update useForm hook with error logic
- Refactor createClinicForm to use the new features of hook
:)
=> Refactor: add error handling logic to useForm hook

package-lock.json, package.json, src/app/main/landlord/create-clinic/page.tsx, src/app/main/landlord/create-clinic/steps/PropertyProofSection.tsx, src/app/main/landlord/create-clinic/steps/RentDataSection.tsx, src/app/main/landlord/create-clinic/steps/StepSectionBase.tsx, src/hooks/useCreateClinicForm.ts, src/lib/apiUtils.ts, src/services/ClinicAvailabilityService.ts, src/services/ClinicEquipmentService.ts, src/services/ClinicPhotoService.ts, src/services/ClinicService.ts, src/types/clinicTypes.ts
This PR adds logic to create Clinic, ClinicPhoto, ClinicEquipment, and ClinicAvailability on form submission
=> Feature: Submit clinic

package-lock.json, package.json, src/app/main/tenant/clinic-info/[id]/components/ReserveCard.tsx, src/app/main/tenant/clinic-info/[id]/page.tsx, src/components/Modal/Modal.tsx, src/components/Modal/index.ts, src/components/TextInput/TextInput.tsx
This PR implements the reservation request feature for clinic rentals. It adds a new ReserveCard component that allows tenants to select dates and submit a rental request for clinics. The implementation includes:
- Enhanced ReserveCard component with date selection functionality
- New Modal component for the reservation confirmation flow
- Integration with the clinic information page
- Improved user experience with clear feedback during the reservation process
- Created a new Modal component for displaying the reservation confirmation
- Enhanced the ReserveCard component to handle date selection and reservation submission
- Added validation to ensure users select at least one date before proceeding
- Implemented loading states during the reservation submission process
- Added comments …
=> feature(clinic-info): add ReserveCard component with reservation modal

src/app/auth/layout.tsx, src/lib/getCookieServer.ts, src/services/AuthService.ts
This PR includes two main authentication improvements:
1. **Fixed Redirect After Authentication**
- Users are now properly redirected to the main page after login/signup
- Resolved issue where users remained on the authentication page after successful authentication
2. **Server-Side Authentication Support**
- Added ability for `AuthService` to retrieve and use auth tokens in server-side components
=> feature(auth): enhance authentication flow for login/signup redirect

src/app/auth/register/page.tsx, src/app/auth/register/steps/BasicInfoSection.tsx, src/app/auth/register/steps/DocumentsSection.tsx, src/components/Image/Image.tsx, src/services/AuthService.ts, src/services/StorageService.ts, src/services/UserService.ts, src/types/userTypes.ts
This PR updates the sign-up flow to adapt/fix to the new backend structure and improves the user registration process.
- Refactored the `UserRegistrationData` type to `CreateUserFormData` to better align with backend expectations
- Updated file upload handling for profile pictures and documents
- Added proper bio field support in registration form
- Improved validation for document uploads
- Fixed image URL handling to support various URL formats (including blob URLs)
- Streamlined storage service to return proper file paths
- Simplified user profile creation and update API calls
- Verified the sign-up process works with the new backend structure
- Tested file uploads for different user types
- Validated form data submission and error handling
=> Sign-Up Flow Refactoring

src/app/auth/register/page.tsx, src/app/main/(shared)/user/edit-profile/components/EditProfileForm.tsx, src/app/main/(shared)/user/edit-profile/page.tsx, src/app/main/(shared)/user/edit/page.tsx, src/components/Navbar/components/UserRightSection.tsx, src/services/UserService.ts, src/types/userTypes.ts
This PR implements the user profile editing functionality, allowing users to update their personal information and delete their accounts if needed.
- **Edit Profile Form**: Created a comprehensive form component that allows users to update:
- Profile picture
- Full name
- Email address
- Phone number
- Bio/description
- Specialty (for tenant users only)
- **Profile Picture Upload**: Users can click on their profile picture to upload a new one, with image preview functionality
- **Account Deletion**: Added functionality for users to delete their account with confirmation modal
- **User Service Updates**: Extended the `UserService` with methods for:
- Updating user profile data
- Deleting user accounts
- **Navigation**: Updated navbar links to point to the new edit profile page route
- …
=> feature(edit-profile): User Profile Editing/deletion Functionality

src/app/main/analyst/metrics/page.tsx
Added a PDF download functionality to the metrics dashboard using the browser's native print capabilities. This provides a simple and reliable way to export dashboard data without requiring external libraries.
- Implemented `handleDownloadPDF` function using browser's print API
- Added print-specific CSS to format the PDF output
- Included cleanup logic to maintain page state
- Uses `window.print()` to trigger browser's print dialog
- Dynamically injects print-specific styles
- Preserves all CSS styling including modern color formats
- Hides UI elements not needed in the PDF output
=> feature(metrics): add PDF download using browser print functionality

src/app/main/landlord/rent-requests/components/LandlordRequestItem.tsx, src/app/main/landlord/rent-requests/components/RentRequestList.tsx, src/components/__missing_section/RentCalendar/RentCalendar.tsx, src/lib/dateUtils.ts, src/types/rentRequestTypes.ts
This PR adds a new Modal to each landlord rent request item, so that it shows a brief summary of the rent request, with appropriate links to profiles and clinics
Preview of review:
=> Feature: add rent request details

src/app/main/(shared)/clinic/[id]/components/ReviewsSection.tsx, src/app/main/(shared)/clinic/[id]/page.tsx, src/app/main/(shared)/user/[id]/components/ListingsSection.tsx, src/app/main/(shared)/user/[id]/components/ReviewsSection.tsx, src/app/main/landlord/past-tenants/components/ReviewModal.tsx, src/app/main/tenant/past-rents/components/PastRentList.tsx, src/app/main/tenant/past-rents/components/PastRentListItem.tsx, src/app/main/tenant/past-rents/components/PastRentsFetcher.tsx, src/app/main/tenant/past-rents/components/ReviewModal.tsx, src/app/main/tenant/past-rents/page.tsx, src/components/Navbar/Navbar.tsx, src/services/ClinicService.ts, src/services/ReviewService.ts, src/types/reviewTypes.ts
This PR implements a comprehensive review system that allows tenants to review both clinics and landlords after their rental period ends. The feature includes UI components, service integrations, and proper data handling.
- **Review System**: Added ability for tenants to rate and review clinics and landlords
- **Past Rents Page**: New page showing tenant's rental history with review functionality
- **Review Display**: Enhanced clinic and user pages to display actual reviews from the database
- `PastRentList.tsx` - Displays list of past rental requests
- `PastRentListItem.tsx` - Individual rental item with review functionality
- `PastRentsFetcher.tsx` - Server component for fetching past rental data
- `ReviewModal.tsx` (tenant) - Modal for submitting reviews for both clinic and landlord
- …
=> Feature: Review System

src/app/main/landlord/metrics/components/EarningsTime.tsx, src/app/main/landlord/metrics/components/EarningsTimeGraph.tsx, src/app/main/landlord/metrics/components/PredictedEarnings.tsx, src/app/main/landlord/metrics/page.tsx, src/components/Navbar/Navbar.tsx
This PR introduces the Landlord Metrics feature, which provides visual insights into landlord earnings via interactive data visualizations. It includes two new chart components, a new metrics dashboard page, and an update to the navigation menu to support access to this new section.
- Weekly earnings visualization using `ComposedChart` (bar + line).
- Accepts `data` and `predictedPercentage` as props.
- Shows a placeholder message when there's no data.
- Monthly earnings comparison (actual vs. predicted) using `AreaChart`.
- Calculates projected growth using `useMemo`.
- Supports `null` actual values for future months.
- Modified landlord navbar links:
- Before: `{ name: "Metrics", href: "/metrics" }`
- After: `{ name: "Metrics", href: "/main/landlord/metrics" }`
- Ensures the "Metrics" …
=> Feature: Landlord Metrics

src/app/main/landlord/edit-clinic/[id]/components/EditForm.tsx, src/app/main/landlord/metrics/components/PredictedEarnings.tsx, src/app/main/landlord/metrics/page.tsx, src/services/PythonService.ts
=> Predicted earnings graph
